[project]
name = "rehlaguide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "amrkhaled100", email = "amrkhalednoser327@example.com" }
]
requires-python = ">=3.10"
dependencies = [
    "chromadb>=1.5.9",
    "fastembed>=0.8.1",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langchain-text-splitters>=1.1.3",
    "sentence-transformers>=6.1.0",
]

[project.scripts]
rehlaguide = "rehlaguide:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
